# Generated by Django 5.0.3 on 2024-03-14 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_product_imageproduct'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='imageProduct',
        ),
        migrations.AddField(
            model_name='grupproduct',
            name='imageProduct',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='grupproduct',
            name='boss',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grup', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='grup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='api.grupproduct'),
        ),
        migrations.AlterField(
            model_name='product',
            name='priceProduct',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='totalProduct',
            field=models.IntegerField(default=0),
        ),
    ]
