# Generated by Django 5.0.3 on 2024-03-14 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_product_imageproduct_grupproduct_imageproduct_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grupproduct',
            old_name='imageProduct',
            new_name='imageGrup',
        ),
        migrations.AddField(
            model_name='product',
            name='imageProduct',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
