# Generated by Django 5.0.3 on 2024-03-14 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_imageproduct_grupproduct_imagegrup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupproduct',
            name='your_boolean_field',
            field=models.BooleanField(default=False),
        ),
    ]
