# Generated by Django 5.0.3 on 2024-03-16 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_grupproduct_imagegrup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupproduct',
            name='imageGrup',
            field=models.ImageField(default='static/image-coming-soon-no-photo-no-thumbnail-image-available-vector-illustration1.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='imageProduct',
            field=models.ImageField(default='static/image-coming-soon-no-photo-no-thumbnail-image-available-vector-illustration1.jpg', upload_to=''),
        ),
    ]
