# Generated by Django 5.0.3 on 2024-03-16 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_grupproduct_imagegrup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imageProduct',
            field=models.ImageField(default='static/image-coming-soon-no-photo-no-thumbnail-image-available-vector-illustration1.jpg', upload_to='your_directory/'),
        ),
    ]
