# Generated by Django 5.0.3 on 2024-03-16 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_product_imageproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupproduct',
            name='imageGrup',
            field=models.ImageField(default='static/def.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='imageProduct',
            field=models.ImageField(default='static/def.jpg', upload_to='your_directory/'),
        ),
    ]
